### ISSUE TITLE
Confirm all Manx is in the newspaper document: Mona's Herald, Feb 21 1872

### ISSUE THREAD

**Issue by david-allison-1** [david-allison-1/manx-search-data#682]
This is very Manx-heavy, with a seemingly different "Pingyn yn Ommidan"

**Comment by robteare** [comment]
Original pamphlet 'pingyn yn ommidan' is a dialogue followed by a song. This version has the song only. I think I have extracted the Manx and given a new title for each piece, e.g.; 'opening address', 'closing address', etc. I am looking at the ballads separately - there are mistakes in the printed Manx, and the translations are unsatisfactory, so going back to original sources, where extant.
