### ISSUE TITLE
Juan Dawson as e Vac / Advert for an ironmongers

### ISSUE THREAD

**Issue by robteare** [david-allison-1/manx-search-data#723]
The title should be 'Juan Dawson as e Vac' - the notes wouldn't go in the right cell.

**Comment by david-allison-1** [comment]
This should be settable in the "Commit Message/Description" in the bottom right of GitHub Desktop. Will fix this up, thanks!

**Comment by david-allison-1** [comment]
Alt+Enter will produce a new line in Excel
