### ISSUE TITLE
Vanninee Ghooghyssagh

### ISSUE THREAD

**Issue by robteare** [david-allison-1/manx-search-data#735]
1. There seems to be a problem of alignment around line 21. 

2. The footnotes at the bottom didn't disappear after being cut and pasted into the notes column - and they don't appear to be hyperlinked.

**Comment by david-allison-1** [comment]
Ref: #734

**Comment by david-allison-1** [comment]
Fixed in https://github.com/david-allison-1/manx-search-data/commit/a69f98f4978fdcd19d8d16f4da1a0d26700e495c#diff-86ec5128021548dd252b7cdae9be948c61118f3f8668fe24723a0a1daa11716e
